### ISSUE TITLE
Improve quality of text when zoomed

### ISSUE THREAD

**Issue by Siccity** [Siccity/xNode#10]
A solution might be to round values after zooming.

**Comment by Siccity** [comment]
Slight improvement. See 2651bfbeb5350e7a1a5a57248df45b613094fee3
Changes should fix blurry text at zoom level 1 due to decimal pan offset.

Could still use improvement

**Comment by Seneral** [comment]
Interested to see what you can come up with - has been bothering me ever since... GUI.scale support sure is bad:(

**Comment by Siccity** [comment]
Hopefully I'll bump into some magical end-all solution. If not, I'll probably try to report it as a bug somehow.
