### ISSUE TITLE
private serialized fields don't show ports

### ISSUE THREAD

**Issue by Siccity** [Siccity/xNode#100]
In this node, A and B shoud show similarly but B doesn't show its port.

```csharp
public class NewNode : Node {
	[Input] public float a;
	[Input, SerializeField] private float b;
}
```

**Comment by thejmper** [comment]
[SerializeField] private ports still don't show if they were defined in an abstract class. Using the following code:

`    abstract class testNodeAbstract: Node
    {
        [Input] [SerializeField] private testNodeAbstract node1;
        [Output] [SerializeField] private testNodeAbstract node2;
    }

    class testNodeConcrete: testNodeAbstract
    {
        [Input] [SerializeField] private testNodeAbstract node3;
        [Output] [SerializeField] private testNodeAbstract node4;
    }
`

only node3 and node4 will have usable ports. The others will show, but only as fields.

**Comment by Siccity** [comment]
Phew. That was some workaround
