### ISSUE TITLE
Inherit CreateNodeMenu

### ISSUE THREAD

**Issue by SirPolly** [Siccity/xNode#105]
Hey,
thank you for this awesome library :)

My use case is an ai graph: https://i.imgur.com/rEGd9vU.png
I have different base classes like tasks, method, scorers, ... all deriving from Node. And I want the context menus of all classes deriving from my ai base class under a sub menu. An additional attribute might do the job, like [NodeMenuScope("Tasks")]. My derived AttackTask will then appear under the context menu Tasks/AttackTask.

If you think this is a good idea I can create a patch.

**Comment by Siccity** [comment]
You can use [CreateNodeMenu("Tasks/AttackTask")] directly on your node classes to set a custom context menu. Use forward slashes for sub menus

You can also override GetNodeMenuName in a custom graph editor to change the default behaviour (eg. adding submenus based on other properties)
