### ISSUE TITLE
Editor caching not working properly

### ISSUE THREAD

**Issue by hardrick** [Siccity/xNode#111]
Not sure if it's a bug or a constraint of the implementation, but:

NodeEditorBase<>::GetEditor uses TryGetValue(target, out editor) to check if the editor for the node (target) is already created (cached).
Since TryGetValue uses GetHashCode and Node::GetHashCode uses JsonUtility.ToJson(this).GetHashCode() the comparison takes into account things like node position.
The result is that each node reposition adds new editor instance to the editors list.

	`//NodeEditorBase.cs
		public static T GetEditor(K target) {
			if (target == null) return null;
			T editor;
			if (!editors.TryGetValue(target, out editor)) {
				Type type = target.GetType();
				Type editorType = GetEditorType(type);
				editor = Activator.CreateInstance(editorType) as T;
				editor.target = target;
				editor.serializedObject = new SerializedObject(target);
				editors.Add(target, editor);
			}
			if (editor.target == null) editor.target = target;
			if (editor.serializedObject == null) editor.serializedObject = new SerializedObject(target);
			
			return editor;
		}`

`       //Node.cs
        public override int GetHashCode() {
            return JsonUtility.ToJson(this).GetHashCode();
        }`

**Comment by Siccity** [comment]
Please test branch https://github.com/Siccity/xNode/tree/dev-optimization and tell me if it solves your issue.

**Comment by hardrick** [comment]
> 
> 
> Please test branch https://github.com/Siccity/xNode/tree/dev-optimization and tell me if it solves your issue.

Yeap, caching works properly and Node::OnValidate seems to work as intended.
Tested on 2018.3.5f1.
Thank You.
