### ISSUE TITLE
Nodes lose connection on play

### ISSUE THREAD

**Issue by celinedrules** [Siccity/xNode#114]
When you play a scene, all nodes lose connections.

**Comment by Siccity** [comment]
Can you provide some more information? Unity version? Perhaps a project .zip that has this issue?

**Comment by Gabbersaurus** [comment]
I have the exact same issue, whenever I make changes to the code or play the scene, every connection will disappear. We're running Unity 5.5.0f3, that may be the cause of the bug.  Will try to update the project and then see what will happen.

**Comment by Siccity** [comment]
I'll need a repro project to identify the issue

**Comment by Gabbersaurus** [comment]
We eventually updated to 2018.3.7f1 which fixed the issue for us. I do not have the time currently to give you a repro project, sorry.
