### ISSUE TITLE
CheckDisalowAllocation error on plugin installation in unity 2018.3.4f1

### ISSUE THREAD

**Issue by GabLeRoux** [Siccity/xNode#118]
I just tried installing version 1.6 from unitypackage file and I'm getting the following error when I hit import:

> Fatal Error!  
> CheckDisalowAllocation. Allocating memory when it is not allowed to allocate memory

![image](https://user-images.githubusercontent.com/1264761/53676739-98445a00-3c74-11e9-9d6d-c178f6ab9542.png)

My system memory looks fine, plenty of it available even if chrome is open ;)

Files seems to have been added upon unity restart tho. I'm trying plugin right now to see if it still works.

**Comment by Siccity** [comment]
Not sure. I don't have any part in how the unitypackage is saved or read. I can only guess this is a Unity issue. If it doesn't work for you, try downloading the master branch as a zip and extract it to your Assets folder
