### ISSUE TITLE
Support for undo

### ISSUE THREAD

**Issue by Roni92pl** [Siccity/xNode#135]
I believe this one is very important to make product look much more professional. 
After initial attemtps it turned out to be simpler than expected to do, basically in every editor that correspond to scriptableObject - so we talk graph and node objects mostly - call [https://docs.unity3d.com/ScriptReference/Undo.RecordObject.html](url) at the beggining ongui for example. Also handle creation and destroying of nodes/graphs and thats it.

**Comment by Roni92pl** [comment]
Contant me if need help with it, as im implementing it in my asset

**Comment by Siccity** [comment]
I'm not sure how to handle undoing destroyed nodes

**Comment by Roni92pl** [comment]
Unity handles this:
        public override void OnGUI()
        {
            Undo.RecordObject(target, "ai graph");
Put this in NodeGraphEditor, and youll be able to undo all serialized changes to graph asset file. 
But after deleting node and undo-ing it it won't showup in graph. This is something to do with your NodeGraph class, so you would need to figure out this part. Other than that it basically just works.

**Comment by coty-crg** [comment]
+1 PLEASE

Maybe do a pull request, if you already have it working on your end?

**Comment by Siccity** [comment]
See 2d1a671b71d11cb55339b9c8845c03f54a5efa00
