### ISSUE TITLE
UIElements Editor Api

### ISSUE THREAD

**Issue by m3rt32** [Siccity/xNode#138]
Unity released their new editor scripting system for a while ago. According to them, it has enormous performance benefits. Xnode should switch to this new system as well.
https://blogs.unity3d.com/2019/04/23/whats-new-with-uielements-in-2019-1

**Comment by Siccity** [comment]
That would be a huge undertaking and would break backwards compatibility as well. It won't happen anytime soon.

**Comment by m3rt32** [comment]
Well it doesn't change the fact that performance problems exists on large graphs. Do you have any solution in mind for this ?

**Comment by DylanYasen** [comment]
wtf? why don't you do it yourself then? respect the author.

**Comment by m3rt32** [comment]
Write it from ground up ? Sir, there is already an api for this called GraphView. I was simply asking a way to increase performance in graphs. If you meant writing that performance patch, thats what I was trying to ask.

**Comment by m3rt32** [comment]
Write it from ground up ? Sir, there is already an api for this called GraphView. I was simply asking a way to increase performance in graphs. If you meant writing that performance patch, thats what I was trying to ask.

I am sorry if I misunderstood.
