### ISSUE TITLE
Error when run on Unity 2017.3.0p3

### ISSUE THREAD

**Issue by takaaptech** [Siccity/xNode#15]
Hi,
I just download the latest code on github and try to create Graph and Node,
But there is an error here:
ArgumentNullException: Argument cannot be null.
Parameter name: collection
System.Collections.Generic.List`1[UnityEngine.Object].CheckCollection (IEnumerable`1 collection) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:435)
System.Collections.Generic.List`1[UnityEngine.Object]..ctor (IEnumerable`1 collection) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:58)
XNodeEditor.NodeEditorWindow.DrawNodes () (at Assets/xNode/Scripts/Editor/NodeEditorGUI.cs:216)
XNodeEditor.NodeEditorWindow.OnGUI () (at Assets/xNode/Scripts/Editor/NodeEditorGUI.cs:23)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:295)
UnityEditor.HostView.Invoke (System.String methodName) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:288)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:255)

**Comment by Siccity** [comment]
Thanks for reporting it! It has been fixed :)
