### ISSUE TITLE
onLateGUI must be of a delegate type

### ISSUE THREAD

**Issue by FedoraGameDev** [Siccity/xNode#151]
Using Unity 2019.2.0b4 and receiving error on line 16 of NodeEditorGUI.cs `NodeEditorWindow.onLateGUI: event must be of a delegate type` upon importing into Unity. No modifications have been made.

**Comment by Siccity** [comment]
My guess is that you have a class in your project called Action which isn't in its own namespace, so the compiler gets confused and uses your class instead of System.Action inside xNode.

**Comment by FedoraGameDev** [comment]
Oh. Well that's a darned good guess.
