### ISSUE TITLE
GetNodeTypes() in NodeEditorReflection should be generic

### ISSUE THREAD

**Issue by FedoraGameDev** [Siccity/xNode#152]
In my project, I have at least 2 different node editors I want to create, one for AI and another for dialogue. Each node editor has its own set of nodes and functionality to use, however, with how `NodeEditorReflection.nodeTypes` works, both node editors will show all nodes from each subset of nodes. I.E. currently, I am able to put AI states and decisions inside of dialogue sequences which doesn't make sense.

It would be nice if I could more easily override this behaviour to only pull from specific derivations of Node, I.E. `GetNodeTypes<AINode>` or `GetNodeTypes<DialogueNode>`.

To accomplish this myself, I've:
- Added `GetNodeTypes<T>()` method to `NodeEditorReflection.cs`
- Passed `GetNodeTypes()` through to `GetNodeTypes<T>()` by passing `XNode.Node` as `T`
- Added `AddContextMenuItems<T>(GenericMenu menu)` to `NodeGraphEditor.cs`
- Passed `AddContextMenuItems(...)` through to `AddContextMenuItems<T>(...)` by passing `XNode.Node` as `T`
- override `AddContextMenuItems(...)` in my `NodeGraphEditor` derived class to pass the correct base node.

It would also be nice to hide the base node in these instances, as they are only there as a means to differentiate the different node groups. To accomplish this, I've:
- Created a new attribute `XNode.Node.HideBaseNode`
- Updated `NodeEditorReflection.cs` `GetNodeTypes<T>(...)` to check if the attribute exists and returns an array with only types that derive from the base class if it does
- Added `[HideBaseNode]` to my `AIBaseNode` class

**Comment by Siccity** [comment]
In a node graph editor script you can override GetNodeMenuName(Node) to change where each node appears in the context menu. To hide a certain node from a graph type, simply return null.
For example, check if the passed node derives from a certain base class, and return null if not.

For your base node classes you might want to just mark them abstract. That'll hide them from xNode as well.
