### ISSUE TITLE
Unity random number generator not working properly when a node graph is displayed

### ISSUE THREAD

**Issue by elrod** [Siccity/xNode#159]
I noticed that when running the game in play mode, while simultaneously displaying an xNode graph makes the Unity Random Number generator, generate the same number sequence.

This seems to be due to the `UnityEngine.Random.InitState(typeName.GetHashCode());` instruction in the `NodeEditorPreferences.cs` class, commenting it out makes it work again, but node connections change colors randomly.

**Note** that the issue arises only when the game view and the xNode graph are displayed simoultaneously.

Running InitState again in some parts of my code did not solve the issue, the only way to make it work is to hide the graph view.

**Comment by Siccity** [comment]
Merged fix
