### ISSUE TITLE
Assembly named "Unity" is skipped due to DLL check.

### ISSUE THREAD

**Issue by PhilippCh** [Siccity/xNode#175]
Hi there,

I was wondering why the NodePorts of my classes were appearing only when I put them in a separate assembly from my main classes. I found out that while building the NodePort cache, you check for `assembly.FullName.StartsWith("Unity")`. Turns out, I have two main assemblies, `Core` for non-unity dependant code and `Unity` for Unity-related code.

I hotfixed the line to

```csharp
if (assembly.FullName.StartsWith("Unity") && !(assembly.GetName().Name == "Unity")) {
```

to include my assembly, but surely this is not an ideal solution.

So apart from renaming my assembly, do you have an idea on how to redesign this check so that user-created assemblies named "Unity" are also included in the caching process?

Cheers
Philipp

**Comment by Siccity** [comment]
Try and see if this fixes your issue https://github.com/Siccity/xNode/tree/experimental/175-fix

**Comment by PhilippCh** [comment]
Jup, this fixed it! There's no PR for it yet, right?
