### ISSUE TITLE
Can not copy graph assets with certain nodes sub-assets' names 

### ISSUE THREAD

**Issue by tcmxx** [Siccity/xNode#185]
An example is to create a new Graph and new node types using the default template. Then create a new Graph and add a new node to it, without changing the default name. The graph's name will be "New New Node Graph" and the node name will be "New".

So far so good. But then if you copy the graph asset using control+d, or rename the graph asset, weird thing happens: the graph becomes a subasset and the node becomes the root asset.....

This happens if the graph and nodes' names have certain patterns. It is occuring on UNity 2019.3b (probably on 2019.2 as well).....

**Comment by Siccity** [comment]
![image](https://user-images.githubusercontent.com/6402525/64495555-f5f8d500-d29b-11e9-8897-d86b92ad5081.png)
Works as expected on 2019.1.0b3

Haven't tested on newer yet

**Comment by tcmxx** [comment]
Did a bunch of test..seems like a problem with 2019.3's new asset database.....close this issue.
