### ISSUE TITLE
2019.3.0b1 compatibility

### ISSUE THREAD

**Issue by Rafarel** [Siccity/xNode#186]
Hello there!
I wanted to try  xNode on a new project that has been created on Unity 2019.3.0b1
I have a lot of errors on this version, so I tried to import the package on 2019.1.8f1 and everything looks good. Have you tested it on the Unity beta ?
Have a good day, thanks for sharing xNode with us all :)

**Comment by Rafarel** [comment]
Thanks for this very fast answer.
So you plan to keep this package updated ? 
I've just staretd to read the examples, I would like to build a tool for scenario / tutorials.
Thanks ! 🙏

**Comment by Siccity** [comment]
I've kept this package updated for over two years, and I have no plans on stopping :)
If you need help I recommend visiting the discord support server. Answers usually come within a day, if not instant.

**Comment by Siccity** [comment]
xNode seems to work fine on 2019.3.0b4.
However, Unity is throwing a lot of errors, even in an empty project.

I am going to wait for a more stable release before I look further into this.
