### ISSUE TITLE
Renaming a Node changes the Graph Name too

### ISSUE THREAD

**Issue by marcosecchi** [Siccity/xNode#200]
Repro:

1. Create a Graph
2. Create a Node
3. Rename the Node (Right click on Node > Rename)
4. The Graph name is updated with the same Node name

**Comment by Siccity** [comment]
Are you right clicking the node in the Project window or in the xNode window?

**Comment by marcosecchi** [comment]
I am clicking it in the xNode window (this happens also in the xNode basic examples). In the Project window, renaming Nodes is disabled.

**Comment by Siccity** [comment]
Which Unity version are you on?

**Comment by nostek** [comment]
I can't reproduce this. Which xNode version/commit are you using?

also
Unity version: 2019.2.10f1
OS: Windows

**Comment by Siccity** [comment]
Try downloading directly from master. The asset store release is currently several months old

**Comment by marcosecchi** [comment]
@Siccity thanks for the heads up. I'm going to try it right now.

**Comment by marcosecchi** [comment]
Ok, with the non-AssetStore version everything works correctly. Thanks again.

**Comment by eddieray** [comment]
I'm seeing the same problem with the Asset Store download with Unity 5.6.7f1.

Downloading master now to see if it fixes the problem...

**Comment by eddieray** [comment]
Confirmed!  The problem doesn't occur using master on Unity 5.6.7f1.
