### ISSUE TITLE
move Examples from branch to own repository

### ISSUE THREAD

**Issue by StefanoCecere** [Siccity/xNode#202]
ciao
the Examples have some errors, maybe because it's many commits behind

why can't Examples be moved in a own Repository?
like Dialogues examples?
so we could leave the main package as is now, and install all demos/examples directly from the Package manager, for example!

**Comment by Siccity** [comment]
You can pull the examples branch through UPM by adding #Examples to the path in your manifest.json file
`"com.github.siccity.xnode": "https://github.com/siccity/xNode.git#Examples"`
