### ISSUE TITLE
[output] forced to one single connection?

### ISSUE THREAD

**Issue by StefanoCecere** [Siccity/xNode#209]
hi!
not the [output] attribute allows mutiple connections to many nodes
but what if i'd like to allow just a single connection at a time?

**Comment by CeejayZSmith** [comment]
Hi, you can use the the parameter **connectionType** to override this. e.g.

` [Output(connectionType = ConnectionType.Override)] `

**Comment by StefanoCecere** [comment]
thank you! shoudl we write this in the wiki somewhere?

**Comment by Siccity** [comment]
Added to the wiki: https://github.com/Siccity/xNode/wiki/Ports#parameters
