### ISSUE TITLE
Namespace clash

### ISSUE THREAD

**Issue by FlaxenFlash** [Siccity/xNode#21]
Using the namespace XNode causes clashes with scripts that use the built in System.Xml.Linq.XNode class. If this was in my own scripts it wouldn't be a big deal, but I'm running into it in 3rd party scripts (in my case scripts associated with Wwise) that I don't want to have to change each time I update the integration. Changing the namespace to something more specific like Siccity.XNode might be advisable to avoid this.

**Comment by Siccity** [comment]
I can see the issue, but i am not very fond of the idea of adding to the namespace (especially my username). Maybe there is another way?
