### ISSUE TITLE
Play mode errors for graph being destroyed at exit

### ISSUE THREAD

**Issue by eddieray** [Siccity/xNode#213]
Continuation of this issue / Alternative scenario from issue 30 (but that one is closed):

In Editor Play Mode, I create a copy of a graph with Instantiate(graphAsset), so that the editor doesn't write changes to the original asset on disk when I make updates to the in-game graph (the graph is a state machine and each node changes depending on choice made during traversal). This works like a charm. However, when the game exits, I get a console error for each node stating:

Destroying assets is not permitted to avoid data loss.
If you really want to remove an asset use DestroyImmediate (theObject, true);
UnityEngine.Object:Destroy(Object)
XNode.NodeGraph:Clear() (at Assets/EdStuff/xNode/Scripts/NodeGraph.cs:50)
XNode.NodeGraph:OnDestroy() (at Assets/EdStuff/xNode/Scripts/NodeGraph.cs:82)

I'm not sure what the proper fix is, or whether I'm going about this the wrong way.

**Comment by Siccity** [comment]
Use graph.Copy() instead of instantiate

**Comment by eddieray** [comment]
Okay... that makes sense.  However, I have one problem with the Copy() results - it changes the names of all the nodes in the graph.  How can I avoid that?
