### ISSUE TITLE
Abstract base NodeEditor

### ISSUE THREAD

**Issue by aauty82** [Siccity/xNode#226]
I am looking to use an abstract base editor class for all nodes in my graph with base functionality.

I am currently missing a method similar to Unity's **Editor.DrawDefaultInspector**.

You mention in the documentation that **NodeEditor** classes cannot be abstract.

What would you suggest to add functionality to a base Editor class so I don't have to have an editor for every child node in my graph?
The specific use case I am looking for is to change tint on nodes at runtime for debugging purposes.

Loving the library! Amazing work!

Cheers,
Aaron.

**Comment by Siccity** [comment]
Just don't mark it abstract

**Comment by aauty82** [comment]
Hey Siccity, thanks for getting back so quick.

Just to double check.

If I make the base class concrete, and override OnBodyGUI() in the base class, I will be missing the node's PropertyField's unless I extend the base class for each child and create PropertyField's for each field?

Would you suggest doing something with reflection? I have 100 child classes and growing!

**Comment by aauty82** [comment]
Nevermind, calling;

base.OnBodyGUI() is what I was after, cheers.
