### ISSUE TITLE
Drag Threshold for Editor Window

### ISSUE THREAD

**Issue by chrisfairc** [Siccity/xNode#228]
Hi, xNode is brilliant. I am facing an issue with it on my mac though.

The scrollable draggable graph editor window is the biggest draw for me in xNode, however since I have a large screen, most of the time my clicks are interpreted as drags and I don't get a context menu when I right-click.

I was hoping to hack a fix by just setting EventSystem.current.pixelDragThreshold higher but EventSystem.current is null for Editor events. Is there a way where I can set a custom drag threshold to make the graph editor usable on larger screens?
Thanks.

**Comment by Siccity** [comment]
Not currently, no. But if you want to try to implement it, you probably have to open up NodeEditorAction.cs

**Comment by chrisfairc** [comment]
Ok. I might send you a PR in a while. Thanks!
