### ISSUE TITLE
Usage from a DLL

### ISSUE THREAD

**Issue by rakkar1974** [Siccity/xNode#23]
As written, version 1.3 can't be used from a DLL. This is the fix:

`
public static Type[] GetDerivedTypes(Type baseType) {
			// KevinJ: 3/23/2018 Allow to be used from a DLL
			List<System.Type> types = new List<System.Type>();
			System.Reflection.Assembly[] assemblies = System.AppDomain.CurrentDomain.GetAssemblies();
			foreach (var assembly2 in assemblies)
			{
					types.AddRange(assembly2.GetTypes().Where(t =>
					!t.IsAbstract &&
					baseType.IsAssignableFrom(t)
				).ToArray());
			}
			return types.ToArray();
        }
`

Also:

`
private static void BuildCache() {
	portDataCache = new PortDataCache();
	System.Type baseType = typeof(Node);
	// KevinJ: 3/23/2018 Allow to be used from a DLL
	List<System.Type> nodeTypes = new List<System.Type>();
	System.Reflection.Assembly[] assemblies = System.AppDomain.CurrentDomain.GetAssemblies();
	foreach (var assembly in assemblies)
	{
	nodeTypes.AddRange(assembly.GetTypes().Where(t =>
	!t.IsAbstract &&
	baseType.IsAssignableFrom(t)
	).ToArray());
	}
	for (int i = 0; i < nodeTypes.Count; i++) {
	CachePorts(nodeTypes[i]);
	}
}`

**Comment by Siccity** [comment]
Your implementation of BuildCache is very slow (measured 2475% increase in processing time).
Could we maybe do something to prevent this? 
Some of my suggestions include checking if xNode itself is in a custom DLL, if not, only check the default DLL
```csharp
Assembly selfAssembly = Assembly.GetAssembly(baseType);
if (selfAssembly.FullName == "Assembly-CSharp") {
  // If xNode is not used as a DLL, check only CSharp (fast)
  nodeTypes.AddRange(selfAssembly.GetTypes().Where(t => !t.IsAbstract && baseType.IsAssignableFrom(t)));
} else {
  // Else, check all DDLs (slow)
  foreach (Assembly assembly in assemblies) {
    nodeTypes.AddRange(assembly.GetTypes().Where(t => !t.IsAbstract && baseType.IsAssignableFrom(t)).ToArray());
  }
}```

**Comment by rakkar1974** [comment]
Disregard, it actually doesn't work due to a bug in Unity. Unity will report in the Inspector that the nodes in the scriptable object cannot be resolved. It will actually still work until you restart unity, at which point the scriptable object will be empty (the nodes were in memory only).

**Comment by rakkar1974** [comment]
Update: Additional work needed to be done for usage from a DLL. In NodeGraph.cs, AddNode(), CopyNode(), and RemoveNode() had #if UNITY_EDITOR which won't work from a non-editor DLL.

I fixed it using a delegate callback
[NodeGraphDelegate.zip](https://github.com/Siccity/xNode/files/1853514/NodeGraphDelegate.zip)

**Comment by Siccity** [comment]
There. Better? :)

**Comment by rakkar1974** [comment]
Actually no. In Unity a DLL has to either be an editor DLL or not an editor DLL, it can't be both. The delegate callback is the correct solution.

**Comment by Siccity** [comment]
What stops you from doing that now that I've gotten rid of the editor code from the NodeGraph script?

**Comment by rakkar1974** [comment]
OK Disregard. I have a lot of modifications I didn't fully look at your changes.
