### ISSUE TITLE
Node disappears after restarting Unity.

### ISSUE THREAD

**Issue by RedTheKitsune** [Siccity/xNode#233]
After creating node in Node Graph, saving it and restarting Unity, node disappears from Node Graph.
Here is the code of Node:

```csharp
public class CombineCoordinates : XNode.Node 
{
        [Input] public int X, Y;
        [Output] public Coordinates Coordinates;
        public override object GetValue(XNode.NodePort port)
        {
            Coordinates.x = GetInputValue<int>("X", this.X);
            Coordinates.y = GetInputValue<int>("Y", this.Y);
            return Coordinates;
        }
}
```

I think it's related to non primitive object outputted by node. Coordinates struct is marked as serializable, so I think xNode should work with serializable data.

**Comment by ReenduX** [comment]
I marked class as Serializable but still no changes.

**Comment by Siccity** [comment]
Are you using any custom editors for nodes or graphs?

**Comment by ReenduX** [comment]
I figured it myself. When using custom data as input/output, the class needs to be in its own script. So I can't have multiple classes in one script, which is kinda weird.

**Comment by Siccity** [comment]
That hasn't been the case always. I have been able to do that just fine in Unity2018. My best guess is Unity broke it in whichever version you are using.

**Comment by ReenduX** [comment]
I'm using 2019.3.0f5. I will check it later with 2019.3.2f1.
