### ISSUE TITLE
Duplicating a graph with renamed nodes results in a incoherent asset

### ISSUE THREAD

**Issue by OscarAbraham** [Siccity/xNode#235]
When one duplicates a graph with at least one node that has been renamed, the main object of the new asset becomes one of the nodes instead of the graph. The node that becomes the main object and it also takes the name of the new asset. I think this is a new behaviour of the new asset database in Unity.  

Using this line before the asset import in the RenamePopup fixes it.
`AssetDatabase.SetMainObject((target as XNode.Node).graph, AssetDatabase.GetAssetPath(target));`

I think this might be a Unity bug, but I have reported it some time ago and there haven't been any fixes. Maybe it's supposed to work like that? But the fix for it is really easy to do anyway, and it is compatible with previous versions of Unity. So maybe xNode should take care of it? 

Would it help if I did a pull request? I've never done one on Github though, so it could take me a some time to learn how to; but I'll do it if it helps.

**Comment by Siccity** [comment]
Thanks for the fix. I'll add it later today, no need to worry about PRs

**Comment by Siccity** [comment]
Added 1ef389689307a761d0b22434cb408a65344df85c
