### ISSUE TITLE
Wiki issue: Filter which nodes are shown in creation menu

### ISSUE THREAD

**Issue by FedoraGameDev** [Siccity/xNode#241]
Page: https://github.com/Siccity/xNode/wiki/Graph-Editors

```
public override string GetNodeMenuName(Node node) {
    if (node is GamePhaseBaseNode)) {
        return base.GetNodeMenuName(node);
    } else return null;
}
```

```
public override string GetNodeMenuName(Type type) {
    if (type is GamePhaseBaseNode)) {
        return base.GetNodeMenuName(node);
    } else return null;
}
```

In the current version of xNode, `GetNodeMenuName(Node node)` is now `GetNodeMenuName(Type type)`. When using the above code snippet with the correct override signature, I get a warning `The given expression is never of the provided ('GamePhaseBaseNode') type.`

Sure enough, when logging the expression, it always shows false and my node is not shown in the context menu.

Blame: https://github.com/Siccity/xNode/blame/master/Scripts/Editor/NodeGraphEditor.cs

According to the above blame, `GetNodeMenuName(Node node)` never existed. Even when it was originally added as `GetNodePath(Type type)`, the Node type was never passed in. attempting to use Node as the passed parameter gives a compile time error `No suitable method found to override` which makes sense as it doesn't exist.

This being said, what would be the proper way of filtering node types? For now, I'm going to continue using the method I created in #152.

**Comment by lbandy** [comment]
I recently had the same issue and after spending some time trying to get it to work I found a solution on the Discord server. Creating a new Editor file for each separate Editor type works well:

```
using System;
using XNodeEditor;

[CustomNodeGraphEditor(typeof(CustomNodeGraph))]
public class CustomNodeEditor : NodeGraphEditor
{
    public override string GetNodeMenuName(Type node)
    {
        // only allow this node type to show up in the Editor
        if (node == typeof(CustomNodetype))
        {
            return base.GetNodeMenuName(node);
        }
        else
        {
            return "";
        }
    }
}
```
I hope this helps.

**Comment by Siccity** [comment]
This is already part of the wiki page on graph editors: https://github.com/Siccity/xNode/wiki/Graph-Editors#tips

**Comment by Siccity** [comment]
Ah my mistake. I see it now. Will do something about it today

**Comment by Siccity** [comment]
Updated the wiki page!
