### ISSUE TITLE
Node.graph still points to prefab on instantiated NodeGraph

### ISSUE THREAD

**Issue by rakkar1974** [Siccity/xNode#25]
Repro along these lines:
NodeGraph myGraph = Object.Instantiate(prefab);
if (myGraph.nodes[0].graph == prefab) Debug.LogError("ERR");
else Debug.Log("OK");

I was able to work around this via:
foreach (Node n in myGraph.nodes)
{
if (n != null)
n.graph = myGraph;
}

**Comment by Siccity** [comment]
Instantiating a ScriptableObject creates only a shallow copy, keeping the same references instead of creating new objects.
NodeGraphs supports deep copy though. See [NodeGraph.Copy();](https://github.com/Siccity/xNode/wiki/NodeGraph.Copy)
```csharp
MyNodeGraph myGraph = prefab.Copy() as MyNodeGraph;
```

**Comment by rakkar1974** [comment]
I would like to suggest adding a Copy() function to Node.cs so that nodes can do a deep copy when necessary
// KevinJ: Added Copy() so Nodes can do a deep copy
public virtual void Copy(List<Node> oldNodes, List<Node> newNodes) {}
