### ISSUE TITLE
Auto Format Node Graphs

### ISSUE THREAD

**Issue by stefnotch** [Siccity/xNode#259]
**Problem**
Manually laying out node graphs takes a while. Furthermore, many people just skip doing it.
So, you can end up with node graphs like this one or worse (this one is actually reasonably neat)

https://twitter.com/jazzmickle/status/1227010568198000642/photo/1

**Suggested Solution**
The ability to select a few nodes and then `Auto Format` them would be really neat.
*I would be willing to create a PR that implements this.*

**Additional Info**
It's not entirely clear how the nodes should be formatted and what sort of formatting rules they should obey. To get the discussion started, a possible algorithm would be the Sugiyama method and/or some possible formatting rules would be [the ones outlined in this tweet](https://twitter.com/joewintergreen/status/1212954361036279808).

**Comment by Siccity** [comment]
This could entirely be an add-on, maintained separately from the base package.

**Comment by stefnotch** [comment]
For what it's worth, I've started implementing it entirely separately from xNode [over here](https://github.com/stefnotch/xnode-graph-formatter)

**Comment by Siccity** [comment]
Nice! I added a link to your repo in the [wiki](https://github.com/Siccity/xNode/wiki)
