### ISSUE TITLE
SceneGraph node lose after reopen scene.

### ISSUE THREAD

**Issue by skmang** [Siccity/xNode#261]
## Description
![image](https://user-images.githubusercontent.com/34685375/81470307-c03a3080-921c-11ea-9b7a-a267ab21fc7f.png)
I create scene graph in this scene, and add some node in this graph. These node may reference some game object in the scene : 
![image](https://user-images.githubusercontent.com/34685375/81470337-de079580-921c-11ea-8870-b416b51cabf8.png)
After i close this scene and reopen, some node in this graph lost:
![image](https://user-images.githubusercontent.com/34685375/81470355-f8417380-921c-11ea-8430-99d7abccc16e.png)
It seem like all node has reference on scene gameobject lost:
![image](https://user-images.githubusercontent.com/34685375/81470463-73a32500-921d-11ea-91c2-3197b277f204.png)
But in the scene file, these lost nodes infomation still exist, for example：
![image](https://user-images.githubusercontent.com/34685375/81470482-84ec3180-921d-11ea-9dbd-847e43d11a89.png)
## Question ❓ 
1. Does scene garph can reference gameobject in scene?
2. Has anyone enconunter this problem before and any solution?
Thank you

**Comment by tabuto74** [comment]
https://github.com/Siccity/xNode/wiki/FAQ

**Comment by skmang** [comment]
My fault. I create some derived node class in same .cs file. 
These class can serialize but can't deserialize correctly.
😆 In case anyone has the same stupid problem, remember create every derived node class in different file!
