### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by codewing** [Siccity/xNode#264]
Since the last release version is quite old I would love to see a newer version so that we can update our dependencies from time to time.

**Comment by Siccity** [comment]
I actually considered deleting the releases entirely as they are always out of date anyway, and it's a chore to update them.

I recommend downloading straight from the master branch instead.

**Comment by codewing** [comment]
The problem is that if we want to use xNode as a dependency for a module we cannot use the git url anymore and have to host a specific version on our own.

For this to work we would only need a tagged version (with the corresponding version in the manifest.json). No built .unitypackage etc.

**Comment by Siccity** [comment]
How exactly did you set your dependency up? UPM? Can upm not reference a specific commit? If you have the option to use git submodules you can reference a specific commit.

**Comment by codewing** [comment]
If you use the "direct" way you can specify xNode as a git dependency in your Packages/manifest.json

However this does not work for subpackages i.e. if you create a package that uses this package you MUST use the package name + a semantic version number. 

This post explains that this is by design:
[custom-package-with-git-dependencies](https://forum.unity.com/threads/custom-package-with-git-dependencies.628390/#post-4208902)

**Comment by Siccity** [comment]
When you said 'release' were you referring to to the .unitypackages in the release tab here on github, or the version tags in git?

**Comment by codewing** [comment]
Version tags in git (+ same version number in the package.json) would be enough for me.

.unitypackage files are not needed but a github release based on the tags for automatic updates would be awesome

**Comment by Siccity** [comment]
Ah, I thought you were talking about the .unitypackage files 😄 
I can start doing version tags, no problem.

**Comment by codewing** [comment]
Awesome! Looking forward to the next release then :)
Thanks a lot!
---
I guess I was too unspecific then :D
And i hope nobody requests them anymore when they can use it as a upm package!
