### ISSUE TITLE
NodeGraph.Copy() will crash on a null node

### ISSUE THREAD

**Issue by rakkar1974** [Siccity/xNode#27]
In NodeGraph.nodes, if there is a null value in that list, NodeGraph.Copy() will crash in the Copy() function. A null value can result from changing the size property in the inspector of the scriptable object. It can also result from deleting a type formerly used.

Fix:

[copyFix.txt](https://github.com/Siccity/xNode/files/1886338/copyFix.txt)

**Comment by Siccity** [comment]
Fixed 588fc0d80a965cae821423cdb8ae6f0440afc660
