### ISSUE TITLE
Field cannot be both input and output

### ISSUE THREAD

**Issue by masonwheeler** [Siccity/xNode#271]
I just ran across this.  Apparently if you try to mark a field as both `[Input]` and `[Output]`, it crashes because there's code in `NodeDataCache` that specifically disallows it.

What's the rationale for this seemingly arbitrary decision?  There are plenty of legitimate reasons why you might want to use an input value in a node and also flow it through for the next node to use.  Is there any way to fix this, besides duplicating the fields?

**Comment by Siccity** [comment]
Ports are stored in a dict and are accessible by a string key. If a field were to be both input and output it would mean two ports with the same key. It's an implementation limitation.
