### ISSUE TITLE
can add callback. createnode or removenode?

### ISSUE THREAD

**Issue by ChuKuang** [Siccity/xNode#274]
to limit operation

**Comment by Siccity** [comment]
You can add RequireNode attribute to your graph to force at least one node of any type in that graph, and override GetNodeMenuName to return null when that node is passed

**Comment by ChuKuang** [comment]
thanks!!!

**Comment by ChuKuang** [comment]
> You can add RequireNode attribute to your graph to force at least one node of any type in that graph, and override GetNodeMenuName to return null when that node is passed

thanks
