### ISSUE TITLE
NodeGraphEditor has bug

### ISSUE THREAD

**Issue by ChuKuang** [Siccity/xNode#276]
CustomGraphEditor， when  override OnGUI,  EditorGUILayout.TextField can not focus.
It seems to be rapainting all the time, resulting in the loss of focus

**Comment by ChuKuang** [comment]
I found the reason  . only node has focus.  so,how to add  EditorGUILayout.TextField outside the node??? 
![微信截图_20200703174600](https://user-images.githubusercontent.com/20549836/86456718-14f9b380-bd55-11ea-8b13-d1b69adc8291.png)

```
  graphEditor.OnGUI();
   public virtual void OnGUI() { }
```
```
   else if (!IsHoveringNode) {
                            // If click outside node, release field focus
                            if (!isPanning) {
                                EditorGUI.FocusTextInControl(null);
                                EditorGUIUtility.editingTextField = false;
                            }
                            if (NodeEditorPreferences.GetSettings().autoSave) AssetDatabase.SaveAssets();
                        }
```

**Comment by Siccity** [comment]
This is due to the way IMGUI captures inputs from the bottom-up. Not much i can do about that.
