### ISSUE TITLE
Edits to node classes are not reflected on existing graphs

### ISSUE THREAD

**Issue by masonwheeler** [Siccity/xNode#277]
In Unity, if you edit a MonoBehaviour to add a new field to it, as soon as Unity recompiles, the changes become visible in the Inspector, even for existing objects in a scene.  But if you add a new input or output field to a Node class, existing nodes on graphs will never be updated because the port list is already established as part of the serialized object.  And worse still, because of the awkward way in which the serialization is done, with two distinct arrays of Keys and Values rather than a single array of pairs, and validation in the deserialization callback that errors out immediately if the two do not match, it's not even possible to add a new port manually in the Inspector!

Expected behavior on Unity is that serializable objects get updated to match the latest version of their class definitions.  xNode fails to follow this rule.  That needs to be fixed, either with something that validates the ports automatically at deserialization time, or at the very least with an option for the developer to manually tell it to sync.

**Comment by Siccity** [comment]
Can't reproduce this bug on 2019.4.0f1. Which version of Unity are you using? Can you attach a test project?

**Comment by masonwheeler** [comment]
2019.3.10f1.  Haven't upgraded to 4 yet because of unsolved serialization bugs that break GKC, which I'm using.

I would upload a sample project, but Internet is currently out at my place.  Sending this on my phone. I'll try this evening after work.

**Comment by masonwheeler** [comment]
All right.  Apparently this does work correctly in the simplest possible case.  I'll go through the code and try to figure out why it doesn't work in the more complicated case my project is using, and see if I can come up with a root cause.

**Comment by masonwheeler** [comment]
All right, I've got a repro case worked out.  Basically, while xNode does correctly update for changes to fields, it does not for changes to dynamic ports, as shown by the graph in `\Assets\Nodes`.  This buggy graph was created by adding the two lines to the constructor one at a time.

[XNodeRepro.zip](https://github.com/Siccity/xNode/files/4885102/XNodeRepro.zip)

**Comment by Siccity** [comment]
Dynamic ports, by definition, are serialized into the node and then _not_ modified by xNode internals. If you are using dynamic ports then you have to manage them yourself. This is by design.

**Comment by masonwheeler** [comment]
Sure seems like xNode internals *is* modifying them.  The constructor, by definition, runs before anything else (such as deserialization).  So it's taking dynamic ports that already exist on the object since construction *and modifying them* by throwing them away.  How do I work around this design?

**Comment by Siccity** [comment]
I think maybe unity gets confused by the constructors. Generally when working with serialization you shouldn't use constructors for Monobehaviours or ScriptableObjects. Use OnEnable instead. Or in xNodes case, use the Init method which is called on initialization.

**Comment by masonwheeler** [comment]
That works.  Putting it in `Init` fixes the problem.  Thanks!
