### ISSUE TITLE
 Pop display position is wrong when zooming graph

### ISSUE THREAD

**Issue by ChuKuang** [Siccity/xNode#278]
Enum Pop display position is wrong when zooming graph

![微信截图_20200713165252](https://user-images.githubusercontent.com/20549836/87284981-91e11600-c529-11ea-9dd3-ef5d17c759ee.png)
![Snipaste_2020-07-13_16-55-17](https://user-images.githubusercontent.com/20549836/87285059-a6251300-c529-11ea-9a75-d0f2f9fdbee5.png)
![image](https://user-images.githubusercontent.com/20549836/87285109-b3da9880-c529-11ea-9cfd-49a2e95ddc6c.png)

**Comment by Siccity** [comment]
This is a Unity bug. As a workaround you can add the [NodeEnum] attribute to the field
