### ISSUE TITLE
Node Enum dropdowns drawn in wrong position when zoomed out

### ISSUE THREAD

**Issue by AphexRebellion** [Siccity/xNode#28]
Click on an enum dropdown in a node when zoomed 1:1 - all ok.
Zoom out and the resulting dropdown is drawn in the wrong position.

**Comment by Siccity** [comment]
Sorry, that is a Unity bug. Apparently the enum pop-up drawer doesn't support GUI scaling

**Comment by AphexRebellion** [comment]
Bah!
