### ISSUE TITLE
runtime evaulation of the node graph

### ISSUE THREAD

**Issue by TheBricktop** [Siccity/xNode#281]
Apart from adding the scene Graph to any object, is there a proper way to connect the graph to the update cycle of unity? 
Should the update events be handled from Scene Graph itself and then the booleans be forwarded to the nodes ?
There is the runtime math example but its not really clear to me how it translates to the basic xnode workflow .

**Comment by Siccity** [comment]
xNode runs on ScriptableObjects. ScriptableObjects do not get updates like MonoBehaviours do. The only way to get an update on a graph is to call it from a MonoBehaviour
