### ISSUE TITLE
Index out of bounds exception when disconnecting nodes

### ISSUE THREAD

**Issue by kalcott** [Siccity/xNode#29]
Steps to reproduce

- In a class that extends Node, implement OnCreateConnection

```
        public override void OnCreateConnection(NodePort from, NodePort to)
        {
            base.OnCreateConnection(from, to);
            if (from.ValueType != to.ValueType)
            {
                from.Disconnect(to);
            }
            
        }
```
- Connect nodes of two different types and error occurs.

In NodePort **GetReroutePoints(int index)** add a check for a non-negative index

**Comment by Siccity** [comment]
Thank you for the report :)
