### ISSUE TITLE
Default colors are ugly and low contrast

### ISSUE THREAD

**Issue by darthdeus** [Siccity/xNode#296]
I do realize that design and aesthetics are subjective, but looking at an example of a node with an `int` and `float` field, this is how it looks by default:

![image](https://user-images.githubusercontent.com/123374/91774999-5a6a1e00-ebea-11ea-8ae3-8e3b1e069cbd.png)

While maybe the red is at least visible, the dark brown on dark gray-ish background feels like really something one has to focus on intentionally and when zoomed out it looks more like noise than anything.

**Comment by Siccity** [comment]
Colors are generated automatically from type name hash. If you wish to change the defaults, try adding a random number to it and see if the results are any better. If you find a good number feel free to submit a pull request.
https://github.com/Siccity/xNode/blob/b5fb59a84eb69e5ce25ce08da5872054ab2a1817/Scripts/Editor/NodeEditorPreferences.cs#L238

**Comment by darthdeus** [comment]
I see, thanks for the explanation. I'll try messing around with it, though I don't feel that just changing the seed will work, since the colors are being uniformly sampled from the whole RGB space, meaning that basically there's no way to guarantee that the colors will match the rest of the UI at least in contrast.

I'll play around with doing this in HSL where it's much easier to select a subspace of the colorspace where all of the colors look nice. I'm not exactly sure how to choose the subspace off the top of my head, but we'll see. The simplest idea that comes to mind is setting fixed saturation and lightness and only randomize hue (or maybe even vary saturation/lightness a little bit in a small range), which would still yield infinite color palette, but avoiding dark/oversaturated ones.
