### ISSUE TITLE
Question: Continuous Repaint

### ISSUE THREAD

**Issue by MeikelLP** [Siccity/xNode#298]
I'm trying to create a behavior tree editor with xNode and I want to debug the state of my behavior tree.
To do that right now I just do a simple color change in the head label of the node.

Sadly the GUI only updates when this window is in focus or any input is given to it (i.e. mouse movement/hover).

Is it possible to (optionally) force it to repaint in 30fps? I know this can have a bad impact on performance in editor but without this it's basically impossible to debug the graph.

**Comment by jlreymendez** [comment]
I had the same problem when building [planilo](https://github.com/jlreymendez/planilo). Check this [wiki](https://github.com/Siccity/xNode/wiki/Graph-Editors) page out, in the tips section you will find what you need.

**Comment by MeikelLP** [comment]
Weird but I accept that

**Comment by MeikelLP** [comment]
@jlreymendez sadly this does not fix the issue :/

I saw some early-returns but putting a Repaint there didn't fix the issue

**Comment by MeikelLP** [comment]
@jlreymendez Sadly the issue here is that unity does not update any GUI if it is not focused or receives any user input (due to performance). So `OnGUI` will never be called.

**Comment by jlreymendez** [comment]
@MeikelLP If the window is focused it will receive an update. But if you are focused on the game window then you are probably right

**Comment by MeikelLP** [comment]
Yeah and that's the issue. I want it to repaint while I'm ingame. Like the profiler or animator. Because I need live information about the state.

**Comment by Siccity** [comment]
https://github.com/Siccity/xNode/wiki/Graph-Editors
Check out the tips section for repainting each frame

**Comment by MeikelLP** [comment]
@Siccity not helping but thanks anyway I guess?
