### ISSUE TITLE
[Minor Typo]

### ISSUE THREAD

**Issue by srcoulombe** [Siccity/xNode#301]
In [the getting started page](https://github.com/Siccity/xNode/wiki/Getting%20Started), I think the sentence "The [CreateAssetMenu] lets you create an asset file in your Project window through Right-Click > Create > SimpleGraph" needs to be replaced with "The [CreateAssetMenu] lets you create an asset file in your Project window through Right-Click > Create > New Node Graph".

**Comment by Siccity** [comment]
In the example, the graph class is called SimpleGraph, so the entry would be named SimpleGraph. The menu entry gets its name from the class name
