### ISSUE TITLE
Custom Inspectors?

### ISSUE THREAD

**Issue by revolt3r** [Siccity/xNode#311]
What if I would like to keep my node super simple while having a lot of fields in the inspector when you click on the node?
I think it would be very useful to have the possibility to also write custom inspectors for the nodes
![image](https://user-images.githubusercontent.com/11783754/111686221-173f6780-8829-11eb-92a5-a86aac221df5.png)

**Comment by Siccity** [comment]
That is possible. You write node inspector with NodeEditor scripts. You can still use normal Editor scripts to override what happens in the editor.
