### ISSUE TITLE
Property Field: The value overlaps the name

### ISSUE THREAD

**Issue by ChristopherRemde** [Siccity/xNode#316]
![image](https://user-images.githubusercontent.com/39704202/115543645-e3c98000-a2a1-11eb-880b-80b736779de6.png)

First of all, thank you for this awesome plugin!

I'm running into an issue when choosing longer variable names, the displayed name seems to be set to a fixed length, while the value expands with the width of the node. (As seen on the bool, it should read "Use Global Clips"). 
Is there any way to prioritize the width of the name over the value field? Or set the width of the name to a certain length?

Thank you in advance!

**Comment by ChristopherRemde** [comment]
Found the answer myself:

I noticed that this is also happening in normal custom editors, but is just more pronounced in xNodes as they are smaller in width.
To change the width, you can use:

`        EditorGUIUtility.labelWidth = 100.0f; // Replace this with any width
`

Just write it down anywhere in your Custom Node Editor script, or place it before creating a PropertyField.

![image](https://user-images.githubusercontent.com/39704202/116091159-dc8ce280-a6a4-11eb-9320-d79310f2c4d7.png)

**Comment by nostek** [comment]
We use this to get as much information on screen we can, it looks a bit messy sometimes, but worth not having very wide nodes :)
Generics is custom classes where we set it to 0 to allow unity to define the label width it needs.

`
if (iterator.propertyType == SerializedPropertyType.Generic) EditorGUIUtility.labelWidth = 0;
else EditorGUIUtility.labelWidth = Mathf.Max(30, GUI.skin.label.CalcSize(new GUIContent(iterator.displayName)).x + 5);
`

**Comment by ChristopherRemde** [comment]
Hi Nostek, thanks for posting your solution! Can you give me a quick hint what the iterator in this context is? 
Are you just iterating through all SerializedProperties?

**Comment by nostek** [comment]
its this iterator, you need to override the function and hook that code in.
https://github.com/Siccity/xNode/blob/93615e7722eea5ff0c38193d41e183d80ccbe524/Scripts/Editor/NodeEditor.cs#L72

**Comment by ChristopherRemde** [comment]
Got it, thank you! Neat, so this basically minimizes the space the value field takes up and maximizes the space of the name field.
So just for future readers, you could do something like this:

```csharp
public override void OnBodyGUI()
    {
        SerializedProperty iterator = serializedObject.GetIterator();

        if (iterator.propertyType == SerializedPropertyType.Generic)
            EditorGUIUtility.labelWidth = 0;

        else
            EditorGUIUtility.labelWidth = Mathf.Max(30, GUI.skin.label.CalcSize(new GUIContent(iterator.displayName)).x + 5);

    }
```
