### ISSUE TITLE
dynamicPortList: Adding a new item to the list is cloning the previous object from the list

### ISSUE THREAD

**Issue by krystianBooker** [Siccity/xNode#319]
Unity version: 2021.1.10f1
xNode version: 1.8.0

Bug: 
When a node has property, that is a list of a model, 'Output' attribute and, the 'dynamicPortList' is set to true.  Adding a new item to the list will clone the previous item in the list. This only happens when 'dynamicPortList' is set to true.

`[Output(dynamicPortList = true)]
 public List<SomeModel> Options;`

![bug](https://user-images.githubusercontent.com/11728287/121093414-00226d00-c7bb-11eb-91eb-5e5d4e3fba6a.gif)

This also happens when using Odin.

**Comment by Siccity** [comment]
This is intended behavior and consistent with normal Unity arrays.

Additionally, dynamic port lists only work properly when edited through the node. Editing them in the inspector like this is likely to cause issues like the ports not updating with the values in the array.
