### ISSUE TITLE
Can a node have scene assets?

### ISSUE THREAD

**Issue by jasonfloreo** [Siccity/xNode#327]
I saw that Node inherits from ScriptableObject. Does this mean that a node can't hold scene information. For example I might want to store a waypoint to an object in a scene.

Thanks so much for your help!

**Comment by Siccity** [comment]
It can if you use Scene Graphs
https://github.com/Siccity/xNode/wiki/Scene-Graphs

**Comment by loganknecht** [comment]
@Siccity 
Is there a way to support both `SceneGraph` and `NodeGraph`? I'm currently trying to manage an existing codebase that is relying on `NodeGraphs` as the assumed default with a signature like this.

```
public class AIBrainGraph : NodeGraph, IBrainGraph
{
...
}
```

But I think it seems like it's a mutually exclusive decision for what to inherit from.
