### ISSUE TITLE
Can we 'Delay' the node output?

### ISSUE THREAD

**Issue by firdiar-agate** [Siccity/xNode#331]
In some case i want the graph delayed the output, maybe waiting for user interaction
.
example
let say i want to make this xNode as Visual Novel Engine , i dont want the text changed continnously but change when the player click a button (let say next button).
.
could you give me some simple snippet to implement this case?

**Comment by Siccity** [comment]
My example repo does exactly that. It's outdated but the approach still works. You can look at it for examples.
https://github.com/Siccity/Dialogue
