### ISSUE TITLE
{   "author": "Isaac Z. Schlueter <i@izs.me> (http://blog.izs.me/)",   "name": "ini",   "description": "An ini encoder/decoder for node",   "version": "2.0.1",   "repository": {     "type": "git",     "url": "git://github.com/npm/ini.git"   },   "main": "lib/ini.js",   "scripts": {     "eslint": "eslint",     "lint": "npm run eslint -- lib test",     "lintfix": "npm run lint -- --fix",     "test": "tap",     "snap": "tap",     "posttest": "npm run lint",     "preversion": "npm test",     "postversion": "npm publish",     "prepublishOnly": "git push origin --follow-tags"   },   "devDependencies": {     "eslint": "^7.9.0",     "eslint-plugin-import": "^2.22.0",     "eslint-plugin-node": "^11.1.0",     "eslint-plugin-promise": "^4.2.1",     "eslint-plugin-standard": "^4.0.1",     "tap": "^15.0.10"   },   "license": "ISC",   "files": [     "ini.js"   ],   "engines": {     "node": ">=10"   }

### ISSUE THREAD

**Issue by russellmelvin7** [Siccity/xNode#334]

**Comment by russellmelvin7** [comment]
{
  "author": "Isaac Z. Schlueter <i@izs.me> (http://blog.izs.me/)",
  "name": "ini",
  "description": "An ini encoder/decoder for node",
  "version": "2.0.1",
  "repository": {
    "type": "git",
    "url": "git://github.com/npm/ini.git"
  },
  "main": "lib/ini.js",
  "scripts": {
    "eslint": "eslint",
    "lint": "npm run eslint -- lib test",
    "lintfix": "npm run lint -- --fix",
    "test": "tap",
    "snap": "tap",
    "posttest": "npm run lint",
    "preversion": "npm test",
    "postversion": "npm publish",
    "prepublishOnly": "git push origin --follow-tags"
  },
  "devDependencies": {
    "eslint": "^7.9.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "tap": "^15.0.10"
  },
  "license": "ISC",
  "files": [
    "ini.js"
  ],
  "engines": {
    "node": ">=10"
  }

**Comment by masonwheeler** [comment]
Ugh, why does GitHub not have a "flag as spam" feature?
