### ISSUE TITLE
Reorderable Lists don't like to be reordered.

### ISSUE THREAD

**Issue by NeedsLoomis** [Siccity/xNode#347]
Dragging and dropping items is buggy, and appears to break connections as well (routing things to the wrong things).

In my case, Im only overriding the draw element callback, but editor code included just in case.

![Unity_CyCY4LQuII](https://user-images.githubusercontent.com/87632315/177469425-d18a2922-9b20-4408-bfea-97e2f459047a.gif)

![image](https://user-images.githubusercontent.com/87632315/177469478-b7990b33-0e05-4bf4-8513-259344e58697.png)

![image](https://user-images.githubusercontent.com/87632315/177469493-1943a182-b708-47e3-8ad7-52d8ec163ebe.png)

**Comment by Siccity** [comment]
Assuming this is resolved with the merge

**Comment by NeedsLoomis** [comment]
Yeap, all good, sorry for the delayed action!
