### ISSUE TITLE
Missing meta file for "TypeExtensions.cs"

### ISSUE THREAD

**Issue by Trisibo** [Siccity/xNode#354]
The file "TypeExtensions.cs" added in the merge commit "1b64a96d40a0b33b497259bcd680c73c3122c85b" has no corresponding Unity metafile. This is an issue when using the plugin as a package, since Unity can't add a new metafile itself due to the package being immutable, so the code file is ignored, leading to compilation errors:

> Asset Packages/com.github.siccity.xnode/Scripts/TypeExtensions.cs has no meta file, but it's in an immutable folder. The asset will be ignored.

> Library\PackageCache\com.github.siccity.xnode@1b64a96d40\Scripts\NodePort.cs(282,97): error CS1061: 'Type' does not contain a definition for 'IsCastableFrom' and no accessible extension method 'IsCastableFrom' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)

> Library\PackageCache\com.github.siccity.xnode@1b64a96d40\Scripts\NodePort.cs(283,105): error CS1061: 'Type' does not contain a definition for 'IsCastableFrom' and no accessible extension method 'IsCastableFrom' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)

> Library\PackageCache\com.github.siccity.xnode@1b64a96d40\Scripts\NodePort.cs(284,100): error CS1061: 'Type' does not contain a definition for 'IsCastableFrom' and no accessible extension method 'IsCastableFrom' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)

> Library\PackageCache\com.github.siccity.xnode@1b64a96d40\Scripts\NodePort.cs(284,154): error CS1061: 'Type' does not contain a definition for 'IsCastableFrom' and no accessible extension method 'IsCastableFrom' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)

**Comment by Siccity** [comment]
Reverted fa62765daa1aa30d5b624d75506129073889a082
