### ISSUE TITLE
Logo Design: xNode

### ISSUE THREAD

**Issue by baranpirincal** [Siccity/xNode#36]
Hello!

 I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by baranpirincal** [comment]
If you have an idea please share with me, It would be better for me! :)

**Comment by Siccity** [comment]
We've had a little chat about it on the discord channel previously. One of the things we came up with was this
https://cdn.discordapp.com/attachments/361769369879183361/415890971549761536/xnode_logo014.png

**Comment by baranpirincal** [comment]
Hey! I am waiting your feedbacks:

![xn](https://user-images.githubusercontent.com/37786733/41293589-60115294-6e5e-11e8-803a-75a7b155032a.jpg)

**Comment by Siccity** [comment]
I feel like the style clashes a lot with Unity and xNode's themes. It should look more like a part of xNode. Maybe reusing some colors, or integrating some node graph features in the design, maybe a subtle grid backgroundbackground? The arrow thing on the x was clever and could work.
I'm not a fan of the N. It looks intentionally simplified, giving the impression of pixel art relevance.

That's just my completely uneducated assessment, i hope it's not too silly :p

**Comment by baranpirincal** [comment]
@siccity

Thank you for the feedbacks! 

Then we keep the 'X' ,
I will try to reflect xNode theme more ,
And I'll change the 'N' .

After that, I will put here again and we can talk on that as soon as possible. :)

**Comment by baranpirincal** [comment]
![xn22](https://user-images.githubusercontent.com/37786733/41330420-133e2ffe-6edc-11e8-8e1a-490ed67788cc.jpg)

**Comment by Siccity** [comment]
That looks much better imo! :)
I'm leaning most towards the middle ones.
Not sure if i like the big or the small grid versions better, but they are both very good. The node header above the text is definitely a big plus too. I'm thinking maybe we should try some different fonts? The colored ports on the x is clever but im not sure if that makes the x too messy.

**Comment by baranpirincal** [comment]
Hey again! :)

I changed the typeface.
Also tried  another X made by circles.

In my opinion third one is best. We should provide some differentiate.

First one with no-risk :)

I am waiting your feedback

![xn33](https://user-images.githubusercontent.com/37786733/41345918-a3140528-6f0d-11e8-9496-3413c391c63d.jpg)

**Comment by Siccity** [comment]
I think this time we went in the wrong direction. I don't like the sharpness of the N, and the details on the X makes the logo look too busy, same with the white edges on the third. I liked the previous typeface better.
Consider the logo at a 30x30 resolution; would the features still look good? That is why i also think we should settle with the 4x3 grid.
Good work so far, but my favorite is still the leftmost center in your previous comment :)

**Comment by baranpirincal** [comment]
@Siccity Hello again,

Sorry for that I misunderstood you, I thought you preferred more sharp font.

For now, I made a font variations of the design you liked.

Also, I tried how it look like in 30x30 px.

![son xn](https://user-images.githubusercontent.com/37786733/41386757-cafce4b4-6f8b-11e8-891d-429065b00e8c.png)

![g](https://user-images.githubusercontent.com/37786733/41386872-874942f2-6f8c-11e8-9eca-44f2ec7576f8.png)

**Comment by Siccity** [comment]
I really like those! Especially 2. We can go with that. If you still feel like refining on it you could try out some different shadows and text colors. But it really looks nice as-is :)

**Comment by baranpirincal** [comment]
@Siccity 

Hey!

I uploaded all necessary files of logo design and it's alternative color variations :)

Good luck with that!

![xnodefirstpage](https://user-images.githubusercontent.com/37786733/41445787-96a6616c-7054-11e8-9c1b-e25c23c321d3.jpg)

**Comment by baranpirincal** [comment]
![xnodegithub](https://user-images.githubusercontent.com/37786733/41457148-625577e0-708b-11e8-93d8-a90ab9661ee5.jpg)

**Comment by baranpirincal** [comment]
![xnode-logo-120x120](https://user-images.githubusercontent.com/37786733/41540908-d3bf993e-7319-11e8-99ab-4aa514314931.png)
