### ISSUE TITLE
Adding xNode in Plugins folder

### ISSUE THREAD

**Issue by nostek** [Siccity/xNode#38]
When extracting xNode to the Plugins folder, the Inputs/Outputs doesn't get recognised.

Moving the folder from Plugins to root fixes it, and moving it back brings back the problem.

-Simon

**Comment by Orcolom** [comment]
Could you give more information (Unity version, ...)?

I just tried this by cloning into a fresh project (unity 2018.1.0b10)
Dragged the complete folder to Plugins and the compiler gives 0 errors.
The example projects also still work

**Comment by nostek** [comment]
The problem seems to be that they get separated in to different assemblies, and NodeDataCache only checks one of them.

[https://github.com/Siccity/xNode/blob/9c6fb740642a4ec86e07787df2ab13f73981ad36/Scripts/NodeDataCache.cs#L52](url)
