### ISSUE TITLE
Adding attribute NodeWidth

### ISSUE THREAD

**Issue by nostek** [Siccity/xNode#40]
I suggest adding a NodeWidth(int width) attribute.

`	[SerializeField]
	[Range(0, 5)]
	float testfloat = 0f;
`
Does not get its slider drawn due to the width of the node, expanding it to 450 makes it visible.
But does not make sense for every node, so maybe it should be a attribute.

Ps. Great node editor! :)

**Comment by Siccity** [comment]
You can change the node width by overriding GetNodeWidth in a custom editor

**Comment by nostek** [comment]
Yes, but it's a lot of work for just changing the width. Could be implemented the same way as NodeTint
