### ISSUE TITLE
Use backing value by default on input nodes...

### ISSUE THREAD

**Issue by smanches** [Siccity/xNode#58]
Returning the backing value as default when an Input node is not connected seems better.  Right now you can do it by providing the backing value as the default value, but it's an extra step on every field.

Example Now:
GetInputValue<float>("Health", Health)

Example better:
GetInputValue<float>("HealthDelta") // Automatically returns backing value, which would be default< T > anyway.

Is it an issue with performance, or could the backing values be stored in the data cache?  I haven't looked at what the performance issues would be.

**Comment by Siccity** [comment]
It's a performance thing. Such behavior would require me to use reflection to check which field matches the fieldname signature. Very bad on performance. I do agree it would be a better default though if performance wasn't an issue.
