### ISSUE TITLE
DrawDraggedConnection throws error on disconnect

### ISSUE THREAD

**Issue by dashrava** [Siccity/xNode#59]
**Issue:**
I'm creating instance ports and drawing them manually in the node's custom editor for some temporary stuff, and destroying them immediately when disconnected.

Whenever the port is destroyed, or its drawing is stopped, _while_ disconnecting, xNode throws a dictionary error.

**Repro:**
1) User begins to disconnect a port by dragging

2) (a) **OnRemoveConnection** calls **RemoveInstancePort** on the port
or
2) (b) Custom editor stops drawing the port.

3) User keeps dragging away from the now-destroyed port

4) Error: `KeyNotFoundException: The given key was not present in the dictionary.` thrown by the `portConnectionPoints[draggedOutputTarget].center` dictionary check in **DrawDraggedConnection** in NodeEditorAction.cs.

**Potential fix:**

Add key check to **DrawDraggedConnection**:
`if (draggedOutputTarget != null && !_portConnectionPoints.ContainsKey(draggedOutputTarget)) return;`

**Comment by Siccity** [comment]
Not sure when it was fixed, but this no longer causes issues
