### ISSUE TITLE
Add NodeEditor.OnEnable override

### ISSUE THREAD

**Issue by Ystyr** [Siccity/xNode#64]
Hi Thor! 
I have to do things like: 
SerializedProperty serializedProp = serializedObject.FindProperty("prop"); inside OnBodyGUI!  
Which is definitely not the best way in terms of performance especially if one needs to do it in a loop.
If OnEnable were exposed, we could just use it for the initialization of the editor values.

Best Regards, Alex

**Comment by Siccity** [comment]
Can't you just cache serializedProp?
`if (serializedProp == null) serializedObject.FindProperty("prop");`

**Comment by Ystyr** [comment]
Of course, I did this, but it feels like a hacky solution, in comparison to how we are used to work with SerializedProperty in the custom Editor.
It's just a suggestion, nevermind if it too troublesome :)

**Comment by Siccity** [comment]
If it's available in custom Editor it should be available in xNode :)
I'll look into it.
