### ISSUE TITLE
How to remove invalid node?

### ISSUE THREAD

**Issue by Howld** [Siccity/xNode#65]
https://github.com/Siccity/xNode/blob/bf333ad6b68a926dc6b990454719016118b0242b/Examples/StateMachine/Nodes/Editor/StateNodeEditor.cs#L13-L15

It's not safe to write this, if I add StateNode on my custom FSMNodeGraph. And I have a problem on how to remove this node in node editor.

Error:
<pre>
NullReferenceException: Object reference not set to an instance of an object
XNodeEditor.Examples.StateNodeEditor.OnHeaderGUI () (at Assets/xNode/Examples/StateMachine/Nodes/Editor/StateNodeEditor.cs:15)
XNodeEditor.NodeEditor.OnNodeGUI () (at Assets/xNode/Scripts/Editor/NodeEditor.cs:21)
XNodeEditor.NodeEditorWindow.DrawNodes () (at Assets/xNode/Scripts/Editor/NodeEditorGUI.cs:365)
XNodeEditor.NodeEditorWindow.OnGUI () (at Assets/xNode/Scripts/Editor/NodeEditorGUI.cs:26)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:295)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:288)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:255)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
</pre>

**Comment by Siccity** [comment]
Change `StateGraph` to `FSMNodeGraph`
