### ISSUE TITLE
Minor bug with noodle 

### ISSUE THREAD

**Issue by Kaladrius2trip** [Siccity/xNode#66]
When i am stacking graph editor window to another then noodle have some little offset by Y axis may be X too. When i am detaching this window all work fine. 
[Show bug IMAGE](https://i.imgur.com/CyqfuGA.png)
I think it is tie to that is change header size.
[Offset in header IMAGE](https://i.imgur.com/89LJeJ9.png)

**Comment by Siccity** [comment]
Yeah it's a bug I've had for a while.

> I think it is tie to that is change header size.
> [Offset in header IMAGE](https://i.imgur.com/89LJeJ9.png)

Well spotted! I think you're right. I'll have a look at it :)

**Comment by delmarle** [comment]
here is an ugly way to fix it, there is probably better way but hope that help anyone:
**NodeEditorGui line 254**
`                    to = toRect.center;
         
                        BindingFlags fullBinding = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static;
                        MethodInfo isDockedMethod = typeof( NodeEditorWindow ).GetProperty( "docked", fullBinding ).GetGetMethod( true );
                        if ((bool) isDockedMethod.Invoke(this, null) == true)
                        {
                            //docked
                            to.y += 3;
                        }

                        DrawConnection(from, to, connectionColor);`

**Comment by Siccity** [comment]
Fixed https://github.com/Siccity/xNode/commit/f5856f79119514a9d5799eec78b9573c70599bec
