### ISSUE TITLE
Improve performance and reduce memory allocations

### ISSUE THREAD

**Issue by JulianSchoenbaechler** [Siccity/xNode#67]
Hey there
xNode is a really nice framework as it is simple to use and overall very feature complete. However, what really bugs me is its terrible memory management. So this is really more of a feature request than a bug or issue.

In my specific case, xNode is used as an ingame state machine, meaning that I will check connections and flows on runtime. There are nodes for states, and conditions -> You can link states through conditions to other states. If the conditions are met, the game can switch from one state to another. In my case, I iterate through all nodes **every** frame, to update all condition nodes and check, if the game state is able to change. Why every frame? Well, an other method would be, to build up a whole reactive system that informs every node whenever something relevant changes in the game, and checks if a state could potentially change. This is a hell lot of work and leads to a really confusing reference mess (what informs what and when).
So, the 'Update()' approach it is.

I mean, iterating over some lists of objects to get specific data every frame is not that uncommon and if done correctly, does not cause any heavy heap allocations (cache and buffering variables). Furthermore, I iterate only if necessary.
But sadly xNode does not agree with me on this. The logic for evaluating connections and getting data at node ports performs terrible. The amount of garbage created amazes me. Not really a problem on desktop, but surely on mobile or anything il2cpp based.

Some examples:
- `Node.GetValue()` that I override, forces me to box the value inside a `System.Object` reference, even if it is value typed and it is called multiple times from the framework. For a big node tree that is evaluated per frame this will create unnecessary allocations. But it is not as bad as...
- ... e.g. `NodePort.GetInputValues()`, which creates an object-array and reference-copies in a loop. There are many other methods that use the same approach to iterate through ports and get data which again is always boxed in `System.Object` containers.
- There is no method which I could pass a pre-allocated `List<T>` or something. Stuff gets always re-instantiated and retrieved data is nowhere cached: `GetValue()` gets called repeatedly every time one of my node checks an input port.

At first, I thought: "Well, at least there are generic methods I can use. Maybe I can avoid boxing when accessing value typed variables.". This is what I've found: '[NodePort.cs - line 142](https://github.com/Siccity/xNode/blob/ff97cc4494b32852233a00e5635d42d2de6fcae6/Scripts/NodePort.cs#L142)'
```cs
public T[] GetInputValues<T>() {
    object[] objs = GetInputValues();
    T[] ts = new T[objs.Length];
    for (int i = 0; i < objs.Length; i++) {
        if (objs[i] is T) ts[i] = (T) objs[i];
    }
    return ts;
}
```
This is not how generics are supposed to be used.

What really lacks is an other way to access or iterate through nodes. As framework user, I'm forced to call `GetInputValue()` at some point. ~~Not any collection is exposed (through a property or something) to iterate by myself~~ (*). Also, this is quite the core of the framework -> meaning, to improve and optimize this behaviour, probably a lot of refactoring and rewriting is needed.

These are my two cents, maybe stating some points which are already considered or recorded. I'm currently not able to contribute by myself, but maybe someone is willing to build up from here.

Hopefully I get to make some profiling stats the next few days, which illustrates my descriptions here. I'll report back.

Cheers
Julian

(*) Edit: I correct myself on this -> will investigate the various `IEnumerator`s in `Node.cs`...

**Comment by Siccity** [comment]
Your points are all very valid. Luckily there is already a solution for you :)
Another user made a fork and implemented a solution using `delegates` in place of `GetValue`. He says it performs much, much better.
I have yet to implement this in the main repo, but perhaps you'd be interested in checking his fork out for the time being.
https://github.com/ddalacu/xNode

**Comment by Siccity** [comment]
Development on the delegate branch has reached a working state. It's not completely finished but can be used for a significant performance boost.
https://github.com/Siccity/xNode/tree/delegate-binding

**Comment by Ayfel** [comment]
Will this be added to the master branch?
