### ISSUE TITLE
Restriction to add a Node

### ISSUE THREAD

**Issue by equalent** [Siccity/xNode#72]
Hello!
Is there a way I can hide my Node from the specified Graph. I have two subsystems: Visual Scripting and AI. I need to make VS nodes appear only in VS graph and AI nodes appear only in AI graph.

Best,
Andrey

**Comment by Siccity** [comment]
Create a NodeGraphEditor for each type of graph and override the method `GetNodeMenuName(Type type)` to return null for non-included types. For example, return null on everything not matching certain namespace.

https://github.com/Siccity/xNode/wiki/NodeGraphEditor
