### ISSUE TITLE
Getting current scroll position

### ISSUE THREAD

**Issue by ManHunterGroms** [Siccity/xNode#84]
I want to create node by editor button in current center view.
In current implementation NodeGraphEditor we cannot do this. I think the ability to get a scroll position will be useful in other cases.

![image](https://user-images.githubusercontent.com/4003735/49749014-42d16000-fcb8-11e8-92c9-447d5554211e.png)

**Comment by Siccity** [comment]
You can get and set the node editor center with `NodeEditorWindow.current.panOffset`
https://github.com/Siccity/xNode/blob/6c1af6f4cda16d50b80a970b803ebdd0549a448e/Scripts/Editor/NodeEditorWindow.cs#L62

**Comment by ManHunterGroms** [comment]
> You can get and set the node editor center with `NodeEditorWindow.current.panOffset`

Thank you, it's very helpful for me.
