### ISSUE TITLE
GetNodePath error

### ISSUE THREAD

**Issue by mskfire** [Siccity/xNode#89]
After import has error in console: 
_Assets/Dialogue-master/Scripts/Editor/DialogueGraphEditor.cs(11,26): error CS0115: `DialogueEditor.DialogueGraphEditor.GetNodePath(System.Type)' is marked as an override but no suitable method found to override_
 
base class (NodeGraphEditor) do not have GetNodePath(System.Type) method

how to correct this?

unity 2018.2.17а1

**Comment by nostek** [comment]
`        [Obsolete("Use GetNodeMenuName instead")]		
         public virtual string GetNodePath(Type type) {		
             return GetNodeMenuName(type);		
         }
`
Found in history. 
This issue should be in the Dialogue repositorys Issues.
