### ISSUE TITLE
The primary node that must exist by default in the graph.

### ISSUE THREAD

**Issue by wakeup5** [Siccity/xNode#95]
When I create a graph object, I want to add nodes that should exist by default, such as Animator's "any state," "Entry," and "Exit." 

I have created a primary node in Awake, or tried AddNode in an object created through ScriptableObject.CreateInstance, but something bad has happened, such as the node's name not showing correctly and other errors.

Can I have the created object include the primary node?

**Comment by Siccity** [comment]
Try in a custom NodeGraphEditor, in One able check if the Entry node exists, and if not, create it with NodeGraphEditor.CreateNode. Doing it through the editor might have a better result as it will also save the asset correctly.

**Comment by Siccity** [comment]
https://github.com/Siccity/xNode/blob/96d73bcb81afff60da58259481f34e12b4c07ce2/Scripts/Editor/NodeGraphEditor.cs#L65

**Comment by wakeup5** [comment]
Thank you. I found it. I have updated to the latest version.

One more thing to ask. In addition to checking in OnGUI, can I have the primary node included when the Graph is created?

**Comment by Siccity** [comment]
Not through built-in functionality. You have to use OnEnable or OnGUI
