### ISSUE TITLE
Declaring variables in a node can only use prefab and not object in scene?

### ISSUE THREAD

**Issue by MutimirEr** [Siccity/xNode#98]
When i declare a pubic game object variable i can only assign prefabs to it and not objects from the scene.
I am using xNode to create editing tools for unity and i need to assign an instantiated object as a child of an object in scene. I cant use prefabs for that. 
Any advice would be appreciated.

`public class TestNode : Node {

    public GameObject gameObject;
	// Use this for initialization
	protected override void Init() {
		base.Init();
		
	}

	// Return the correct value of an output port when requested
	public override object GetValue(NodePort port) {
		return null; // Replace this
	}
}`

**Comment by MutimirEr** [comment]
I found a work around.
I use GameObject.FindWithTag to find the parent object by tag so it dosnt have to be assigned in the node.

**Comment by Siccity** [comment]
ScriptableObjects do not support scene references. This is a design choice done on Unity's behalf. There are numerous workarounds though, tags and custom GUID solutions to name a few.

**Comment by Lucaffo** [comment]
Sorry if i re-open this, but it may be quite useful for others.

I have this **exact** same problem in my game.

While working on my game, i start to work on my interaction system and i found about i need more flexibility to graph the state of the interactions.

My interactable simple call an interactable graph that do all the logic and handle all the interaction flow.

If i'd want to implement it with xNode, i should implement some Mediator pattern to mediate messaging from the xNode graph and the actual logic in the game. It's quite odd solution, but absolutly better then static messaging with strings, tags and even GUID.

So, the things is, your xNode simply send messages to the Mediator of your scene, passing the node it self as data. 
I'm actually try to wrap my head around it this means that i cannot test this solution yet, but i think is the right way to approach this kind of problems.

**Comment by nostek** [comment]
There is SceneGraphs for this now
https://github.com/Siccity/xNode/wiki/Scene-Graphs
