### ISSUE TITLE
Color for types in preferences will reseted after playing

### ISSUE THREAD

**Issue by WeslomPo** [Siccity/xNode#99]
When you set color in preferences for type, it will be not saved, and will be reseted after playing or restarting unity.

Also I got error 
```
InvalidOperationException: Collection was modified; enumeration operation may not execute.
System.Collections.Generic.Dictionary`2+Enumerator[TKey,TValue].MoveNext () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
XNodeEditor.NodeEditorPreferences.TypeColorsGUI (System.String key, XNodeEditor.NodeEditorPreferences+Settings settings) (at Assets/Scripts/xNode/Editor/NodeEditorPreferences.cs:139)
XNodeEditor.NodeEditorPreferences.PreferencesGUI () (at Assets/Scripts/xNode/Editor/NodeEditorPreferences.cs:92)
UnityEditor.SettingsService+<FetchDeprecatedPreferenceItems>c__AnonStorey0.<>m__0 (System.String searchContext) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Settings/SettingsService.cs:58)
UnityEditor.SettingsProvider.OnGUI (System.String searchContext) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Settings/SettingsProvider.cs:118)
```
I suppressed it by adding  ` break;` in `EndChangeCheck` if. After that I got two unity crashes, which I associate with xNode. And that tweak don't help me any how :(. Only error message not presented anymore.

**Comment by WeslomPo** [comment]
Other setting not affected. What really strange, that when I write settings - they right, but when it loading it after play - there no colors for type, but other settings seems unaffected.

**Comment by WeslomPo** [comment]
Hm. When I change type color and Highlight color - type saved properly.

**Comment by WeslomPo** [comment]
I found a problem! When settings saves - they use a wrong key
```
SavePrefs(typeColorKey, settings); 
```
`typeColorKey` - is a `float`, solution is
```
SavePrefs(lastKey, settings); // Change this
NodeEditorWindow.RepaintAll();
break; // and add this
```

**Comment by kbornema** [comment]
> 
> 
> I found a problem! When settings saves - they use a wrong key
> 
> ```
> SavePrefs(typeColorKey, settings); 
> ```
> 
> `typeColorKey` - is a `float`, solution is
> 
> ```
> SavePrefs(lastKey, settings); // Change this
> NodeEditorWindow.RepaintAll();
> break; // and add this
> ```

I was just about to post the same issue, when I found this. I tried your solution and it works like a charm! Thanks :)
